import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workspace = path.resolve(root, "..");
const sources = {
  "invoice-escrow": "contracts/invoice-escrow/src/errors.rs",
  "invoice-token": "contracts/invoice-token/src/errors.rs",
  "payment-distributor": "contracts/payment-distributor/src/errors.rs",
};

const definitions = {};
for (const [contract, relativePath] of Object.entries(sources)) {
  const source = await readFile(path.join(workspace, relativePath), "utf8");
  const body = source.match(/pub enum Error\s*\{([\s\S]*?)\n\}/)?.[1];
  if (!body) throw new Error(`Could not find Error enum in ${relativePath}`);

  const errors = [...body.matchAll(/^\s*(\w+)\s*=\s*(\d+)\s*,?\s*$/gm)];
  if (errors.length === 0) throw new Error(`No explicit errors found in ${relativePath}`);
  definitions[contract] = Object.fromEntries(errors.map(([, name, code]) => [name, Number(code)]));
  const codes = Object.values(definitions[contract]);
  if (new Set(codes).size !== codes.length) {
    throw new Error(`Duplicate error code in ${relativePath}; assign unique codes within each contract`);
  }
}

const ts = `// Generated by scripts/generate-errors.mjs from the contract Error enums.\n` +
  `// Run npm run generate after changing a contract error definition.\n` +
  `export const CONTRACT_ERRORS = ${JSON.stringify(definitions, null, 2)} as const;\n\n` +
  `export type ContractName = keyof typeof CONTRACT_ERRORS;\n` +
  `export type ErrorName<C extends ContractName> = keyof (typeof CONTRACT_ERRORS)[C];\n` +
  `export type ErrorCode<C extends ContractName> = (typeof CONTRACT_ERRORS)[C][ErrorName<C>];\n` +
  `export type ContractError = { [C in ContractName]: {\n` +
  `  contract: C;\n` +
  `  name: ErrorName<C>;\n` +
  `  code: (typeof CONTRACT_ERRORS)[C][ErrorName<C>];\n` +
  `} }[ContractName];\n\n` +
  `export function isKnownContractError(contract: string, code: number): boolean {\n` +
  `  if (!(contract in CONTRACT_ERRORS)) return false;\n` +
  `  const errors = CONTRACT_ERRORS[contract as ContractName] as Record<string, number>;\n` +
  `  return Object.values(errors).includes(code);\n` +
  `}\n\n` +
  `export function contractErrorsForCode<C extends ContractName>(contract: C, code: number): ErrorName<C>[] {\n` +
  `  return Object.entries(CONTRACT_ERRORS[contract])\n` +
  `    .filter(([, errorCode]) => errorCode === code)\n` +
  `    .map(([name]) => name as ErrorName<C>);\n` +
  `}\n`;

const variants = Object.entries(definitions).flatMap(([contract, errors]) =>
  Object.entries(errors).map(([name, code]) => ({
    type: "object",
    properties: {
      contract: { const: contract },
      name: { const: name },
      code: { const: code },
    },
    required: ["contract", "name", "code"],
    additionalProperties: false,
  })),
);

const schema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://stellarstate.github.io/ss-contracts/schemas/contract-errors.schema.json",
  title: "StellarSettle JSON-RPC contract error response",
  description: "A JSON-RPC error response whose data identifies a Soroban contract error.",
  type: "object",
  properties: {
    jsonrpc: { const: "2.0" },
    id: { anyOf: [{ type: "string" }, { type: "integer" }, { type: "null" }] },
    error: {
      type: "object",
      properties: {
        code: { type: "integer" },
        message: { type: "string" },
        data: { $ref: "#/$defs/ContractError" },
      },
      required: ["code", "message", "data"],
      additionalProperties: true,
    },
  },
  required: ["jsonrpc", "id", "error"],
  additionalProperties: false,
  $defs: {
    ContractError: { oneOf: variants },
  },
};

await writeFile(path.join(root, "src/errors.ts"), ts);
await writeFile(path.join(root, "schemas/contract-errors.schema.json"), `${JSON.stringify(schema, null, 2)}\n`);
