// Generated by scripts/generate-errors.mjs from the contract Error enums.
// Run npm run generate after changing a contract error definition.
export const CONTRACT_ERRORS = {
  "invoice-escrow": {
    "AlreadyInit": 1,
    "NotInit": 2,
    "Unauthorized": 3,
    "InvalidAmount": 4,
    "InvalidFeeBps": 5,
    "EscrowNotFound": 6,
    "EscrowExists": 7,
    "EscrowFunded": 8,
    "EscrowNotFunded": 9,
    "AlreadySettled": 10,
    "RefundNotAllowed": 11,
    "TransferFailed": 12,
    "Overflow": 13,
    "EscrowCancelled": 14,
    "Paused": 15,
    "InvalidPayer": 16,
    "InvalidDueDate": 17,
    "InvalidAssetDecimals": 18,
    "NonceAlreadyUsed": 19,
    "EscrowNotSettled": 20,
    "NotWhitelisted": 21,
    "SignatureExpired": 22,
    "InvalidMilestoneAmount": 23,
    "CancelNotAllowed": 24,
    "InvalidPenaltyConfig": 25,
    "InvalidPaymentToken": 26,
    "InvalidInvoiceToken": 27,
    "IdenticalTokens": 28,
    "NoPositionFound": 29,
    "InvalidInvoiceStatus": 30,
    "BelowMinimumInvestment": 31,
    "FundingTargetNotReached": 32,
    "ZeroAmount": 33,
    "AmountBelowMinimum": 34,
    "InvalidAddress": 35,
    "InvalidDuration": 36,
    "NotEmergencyAdmin": 37,
    "AlreadyApproved": 38,
    "ThresholdNotMet": 39,
    "EmergencyNotConfigured": 40,
    "InvalidLimit": 41,
    "LimitExceeded": 42,
    "InvoiceAlreadyExists": 43,
    "InvalidYield": 44,
    "FundingDeadlineNotPassed": 45,
    "InsufficientRepayment": 46,
    "DeadlineNotExtended": 47,
    "EscrowOverdue": 48,
    "EscrowNotOverdue": 49,
    "NotDisputed": 50,
    "AlreadyResolved": 51,
    "DisputeTimedOut": 52,
    "InvalidEarlySettlement": 53,
    "InvalidInstallmentSchedule": 54,
    "FeeTooHigh": 55,
    "MaxInvestorsReached": 57,
    "InvalidMaxInvestors": 56
  },
  "invoice-token": {
    "AlreadyInit": 1,
    "NotInit": 2,
    "Unauthorized": 3,
    "RoleNotGranted": 4,
    "InvalidAmount": 5,
    "InsufficientBalance": 6,
    "InsufficientBalanceForFee": 7,
    "InsufficientAllowance": 8,
    "AllowanceExpired": 9,
    "TransferLocked": 10,
    "Overflow": 11,
    "InvalidExpiration": 12,
    "Paused": 13,
    "InvalidDecimals": 14,
    "InvalidMetadata": 15,
    "AllowanceNotFound": 16,
    "BatchLengthMismatch": 17,
    "InvalidFeeBps": 18,
    "AccountFrozen": 19,
    "AccountNotFrozen": 20,
    "InvalidAddress": 21
  },
  "payment-distributor": {
    "AlreadyInit": 1,
    "NotInit": 2,
    "InvalidAmount": 3,
    "Unauthorized": 4,
    "InvalidEscrowStatus": 5,
    "NothingToDistribute": 6,
    "RefundAlreadyDistributed": 7,
    "Overflow": 8,
    "WrongDistributor": 9,
    "InvalidBps": 10,
    "ReentrancyDetected": 11,
    "InvalidReferralCut": 12,
    "SplitsExceedTotal": 13,
    "InvalidSplit": 14,
    "EmptyAssetList": 15,
    "AssetMismatch": 16,
    "NothingToWithdraw": 17,
    "UnauthorizedEscrow": 18,
    "InsufficientBalance": 19,
    "NothingToSweep": 20,
    "EmptyBatch": 21,
    "BatchTooLarge": 22,
    "TooManyFeeRecipients": 23,
    "InvalidFeeSplit": 24,
    "InvalidBonusRate": 25,
    "TooManyRefundRecipients": 26,
    "InvalidRefundWeight": 27
  }
} as const;

export type ContractName = keyof typeof CONTRACT_ERRORS;
export type ErrorName<C extends ContractName> = keyof (typeof CONTRACT_ERRORS)[C];
export type ErrorCode<C extends ContractName> = (typeof CONTRACT_ERRORS)[C][ErrorName<C>];
export type ContractError = { [C in ContractName]: {
  contract: C;
  name: ErrorName<C>;
  code: (typeof CONTRACT_ERRORS)[C][ErrorName<C>];
} }[ContractName];

export function isKnownContractError(contract: string, code: number): boolean {
  if (!(contract in CONTRACT_ERRORS)) return false;
  const errors = CONTRACT_ERRORS[contract as ContractName] as Record<string, number>;
  return Object.values(errors).includes(code);
}

export function contractErrorsForCode<C extends ContractName>(contract: C, code: number): ErrorName<C>[] {
  return Object.entries(CONTRACT_ERRORS[contract])
    .filter(([, errorCode]) => errorCode === code)
    .map(([name]) => name as ErrorName<C>);
}
